[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
age = "1.3.1"
argocd = "3.4.1"
atuin = "18.16.0"
bitwarden = "2026.4.1"
dust = "1.2.4"
eza = "0.23.4"
fnox = "1.24.0"
go = "1.26.3"
github-cli = "2.92.0"
"github:waylonwalker/nvim-manager" = "0.0.3"
gitui = "0.28.1"
helm = "4.1.4"
htmlq = "0.4.0"
helix = "25.07.1"
jq = "1.8.1"
just = "1.50.0"
k9s = "0.50.18"
kubectl = "1.36.0"
lazydocker = "0.25.2"
lazygit = "0.61.1"
lazyjournal = "0.8.6"
lazyssh = "0.3.0"
"aqua:neovim/neovim" = "0.12.2"
pitchfork = "2.10.0"
ripgrep = "15.1.0"
starship = "1.25.1"
television = "0.15.6"
yazi = "26.5.6"
vhs = "0.11.0"
tmux = "3.6a"
ttyd = "1.7.7"
zellij = "0.44.2"
chezmoi = "2.70.3"
grex = "1.4.6"
ripsecrets = "0.1.11"
pnpm = "v10.22.0"
uv = "0.11.12"
node = "26.1.0"
fastfetch = "2.62.1"
fd = "10.4.2"
direnv = "2.37.1"
dua = "2.34.0"
fzf = "0.72.0"
goreleaser = "v2.15.4"
"github:pagefind/pagefind" = "1.5.2"
difftastic = "0.69.0"
delta = "0.19.2"
vfox = "1.0.11"
"github:darksworm/argonaut" = "2.17.0"
"github:janosmiko/lfk" = "0.10.4"
"npm:tailwindcss" = "4.3.0"
"pipx:harlequin" = "2.5.2"
"pipx:ipython" = "9.13.0"
"pipx:lolcat" = "1.4"
"pipx:podman-compose" = "1.5.0"
"pipx:visidata" = "3.3"
"pipx:waylonwalker" = "0.4.6"
