[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
age = "latest"
argocd = "latest"
atuin = "latest"
bitwarden = "latest"
dust = "latest"
eza = "latest"
fnox = "latest"
github-cli = "latest"
"github:waylonwalker/nvim-manager" = "latest"
gitui = "latest"
helm = "latest"
htmlq = "latest"
jq = "latest"
just = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
lazyssh = "latest"
litestream = "latest"
neovim = "latest"
pitchfork = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
vhs = "latest"
tmux = "latest"
zellij = "latest"
chezmoi = "latest"
grex = "latest"
ripsecrets = "latest"
pnpm = "latest"
uv = "latest"
node = "latest"
fastfetch = "latest"
fd = "latest"
direnv = "latest"
dua = "latest"
fzf = "latest"
goreleaser = "latest"
"github:pagefind/pagefind" = "latest"
difftastic = "latest"
delta = "latest"
vfox = "latest"
