#!/usr/bin/bash
# 
# usage
#
# curl https://raw.githubusercontent.com/WaylonWalker/devtainer/main/bootstrap-arch | bash
#

export PATH=$PATH:~/.local/bin
export ANSIBLE_LOCALHOST_WARNING=False

# update the system
sudo pacman -Syu

# setup paru
sudo pacman -S --needed base-devel
sudo pacman -Syu rustup --noconfirm
rustup default stable
mkdir ~/third-party
git clone https://aur.archlinux.org/paru.git ~/third-party/paru
pushd ~/third-party/paru
yes | makepkg -si
popd

sudo pacman -Syu git ansible --noconfirm

ansible-galaxy collection install community.general

[ ! -d ~/devtainer ] && git clone https://github.com/waylonwalker/devtainer ~/devtainer
# ansible-playbook --ask-become-pass ~/devtainer/ansible/local.yml
