[tools]
agent-browser = "latest"
argocd = "latest"
aws-cli = "2"
azure = "2.89.1"
bat = "latest"
github-cli = "latest"
gitui = "latest"
go = "latest"
herdr = "latest"
hunk = "latest"
just = "latest"
k9s = "latest"
kubectl = "latest"
kubeseal = "latest"
lazygit = "latest"
neovim = "latest"
python = "3.10"
starship = "latest"
uv = "latest"
