Output static/tapes/lf-intro.mp4

Require echo

Set Shell zsh
Set FontSize 24
Set Width 1200
Set Height 800

Hide
Type 'cd ~/devtainer/vhs/sandbox' Enter
Type 'clear' Sleep 500ms Enter
Show

Type "lf" Sleep 1s Enter
Sleep 2s

Type "j" Sleep 200ms
Type "j" Sleep 200ms
Type "l" Sleep 500ms
Type "j" Sleep 200ms
Type "k" Sleep 500ms
Type "h" Sleep 1s
Type "G" Sleep 500ms
Type "gg" Sleep 1s
Type "q" Sleep 500ms Enter

Sleep 1s
