Output static/tapes/neovim-lsp-go-to-definition.mp4

Require echo

Set Shell zsh
Set FontSize 24
Set Width 1400
Set Height 900

Hide
Type 'cd ~/devtainer/vhs/sandbox/project-1' Enter
Type 'clear' Sleep 500ms Enter
Show

Type "nvim src/main.py" Sleep 1s Enter
Sleep 3s

Type "gg" Sleep 500ms
Type "j" Sleep 200ms
Type "j" Sleep 500ms

Type "gd" Sleep 1s
Sleep 2s

Type "Ctrl+o" Sleep 1s
Sleep 1s

Type ":q" Sleep 500ms Enter
Sleep 1s
