Output static/tapes/neovim-telescope.mp4

Require echo

Set Shell zsh
Set FontSize 24
Set Width 1400
Set Height 900

Hide
Type 'cd ~/devtainer/vhs/sandbox/project-1' Enter
Type 'clear' Sleep 500ms Enter
Show

Type "nvim" Sleep 1s Enter
Sleep 3s

Type "Space" Sleep 200ms
Type "ff" Sleep 1s
Sleep 2s

Type "main" Sleep 500ms
Sleep 1s
Type "Enter" Sleep 1s
Sleep 2s

Type ":q" Sleep 500ms Enter
Sleep 1s
