WORKSPACE_COUNT=9
CLOCK_FORMAT=12h
DISABLE_UBUNTU_DOCK=true
DISABLE_DESKTOP_ICONS=true
SCREENSHOT_BINDING="<Super><Alt>p"
SCREENSHOT_COMMAND="$HOME/.local/bin/devtainer-gnome-screenshot-area"
WINDOW_NEXT_BINDING="<Super>j"
WINDOW_PREV_BINDING="<Super>k"
CLOSE_WINDOW_BINDING="<Super>c"
TOGGLE_MAXIMIZE_BINDING="<Super>f"
KITTY_FOCUS_BINDING="<Super>Return"
KITTY_NEW_BINDING="<Super><Shift>Return"
CHROME_FOCUS_BINDING="<Super>b"
CHROME_NEW_BINDING="<Super><Shift>b"
FILES_FOCUS_BINDING="<Super>e"
ROFI_WINDOW_BINDING="<Super>w"
ROFI_RUN_BINDING="<Super>r"
MONITOR_SWAP_BINDING="<Super>o"
EMOJI_PICKER_BINDING="<Super>semicolon"
ROFI_THEME_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/devtainer-rofi.rasi"
