# =====================================
# Autostart
# =====================================

# -------------------------------------
# Startup command aliases
# -------------------------------------
$focus_or_launch = ~/.config/hypr/scripts/focus_or_launch.sh
$start_browser = $focus_or_launch brave-browser brave --password-store=basic
$start_terminal = $focus_or_launch kitty kitty
$start_signal = $focus_or_launch Signal signal-desktop

# -------------------------------------
# Startup services and apps
# -------------------------------------
exec-once = waybar
exec-once = hyprpaper
exec-once = bash -lc 'sleep 1; ~/.config/hypr/scripts/restore_wallpaper.sh >/dev/null 2>&1 || true'
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = swaync
exec-once = $start_browser
exec-once = $start_terminal
exec-once = $start_signal
