# Extra autostart processes
# exec-once = uwsm app -- my-service

# $polkit = systemctl --user start hyprpolkitagent
$polkit = /usr/lib/polkit-kde-authentication-agent-1
$notifications = swaync
$focus_or_launch = ~/.config/hypr/scripts/focus_or_launch.sh
$start_steam = $focus_or_launch steam steam
$start_browser = $focus_or_launch brave-browser brave --password-store=basic
$start_terminal = $focus_or_launch kitty kitty
$start_signal = $focus_or_launch Signal signal-desktop
$start_chatgpt = $focus_or_launch brave-chat.openai.com__-Default $webapp="https://chat.openai.com"
$start_youtube = $focus_or_launch brave-youtube.com__-Default $webapp="https://youtube.com"

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = $polkit
exec-once = $notifications
exec-once = $start_browser
exec-once = $start_terminal
exec-once = $start_signal
