# Extra env variables
# Note: You must relaunch Hyprland after changing envs (use Super+Esc, then Relaunch)
# env = MY_GLOBAL_ENV,setting

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# See https://wikihyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Set programs that you use
$terminal = kitty
$start_terminal = ~/devtainer/hypr/.config/hypr/scripts/terminal.sh
$browser = brave --password-store=basic
$webapp = $browser --app
# $fileManager = uwsm app -- nautilus --new-window
$fileManager = uwsm app -- nautilus
# $fileManager = dolphin
$menu = wofi --show drun --insensitive
# $polkit = /usr/lib/polkit-kde-authentication-agent-1
$polkit = systemctl --user start hyprpolkitagent
$notifications = swaync

$focus_or_launch = ~/devtainer/hypr/.config/hypr/scripts/focus_or_launch.sh
$start_steam = $focus_or_launch steam steam
$start_browser = $focus_or_launch brave-browser brave --password-store=basic
$start_terminal = $focus_or_launch kitty kitty
$start_signal = $focus_or_launch Signal signal-desktop
$start_chatgpt = $focus_or_launch brave-chat.openai.com__-Default $webapp="https://chat.openai.com"
$start_youtube = $focus_or_launch brave-youtube.com__-Default $webapp="https://youtube.com"

$start_btop = btop
