# =====================================
# Environment Variables
# =====================================
# Relaunch Hyprland after changing envs.

# -------------------------------------
# NVIDIA
# -------------------------------------
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
