# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
# source = ~/.local/share/omarchy/default/hypr/autostart.conf
# source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
# source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
# source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
# source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
# source = ~/.local/share/omarchy/default/hypr/input.conf
# source = ~/.local/share/omarchy/default/hypr/windows.conf
# source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
# source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
# source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf


####################
### WINDOW RULES ###
####################
windowrule = workspace 1, match:class ^(steam)$
windowrule = workspace 4, match:class ^(kitty)$
windowrule = workspace 5, match:class ^(firefox)$
windowrule = workspace 5, match:class ^(brave-browser)$
windowrule = workspace 5, match:class ^(google-chrome)$
windowrule = workspace 6, match:class ^(signal)$
windowrule = workspace 2, match:class ^(krita)$
windowrule = workspace 8, match:class ^(brave-chat.openai.com__-Default)$
windowrule = workspace 8, match:class ^(brave-youtube.com__-Default)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = workspace 9, match:class ^(org.prismlauncher.PrismLauncher)$
windowrule = float on, match:class ^(org.prismlauncher.PrismLauncher)$, match:title ^(Console window.*)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$

