# =====================================
# Hyprpaper Configuration
# =====================================

# -------------------------------------
# Preloaded wallpapers
# -------------------------------------
preload=/home/waylon/.config/awesome/wallpaper/1440w2.png
preload=/home/waylon/.config/awesome/wallpaper/Dark_Nature.png

# -------------------------------------
# Startup behavior
# -------------------------------------
splash=true
wallpaper=DP-1,/home/waylon/.config/awesome/wallpaper/Dark_Nature.png
