# =====================================
# Hyprland Main Configuration
# =====================================
# Reference: https://wiki.hyprland.org/Configuring/

env = XCURSOR_THEME,breeze_cursors
env = XCURSOR_SIZE,24

# -------------------------------------
# Active Local Config
# -------------------------------------
source = ~/.config/hypr/monitors.conf
# source = ~/.config/hypr/input.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/autostart.conf

####################
### WINDOW RULES ###
####################
windowrule = workspace 1, match:class ^(steam)$
windowrule = workspace 4, match:class ^(kitty)$
windowrule = workspace 5, match:class ^(firefox)$
windowrule = workspace 5, match:class ^(brave-browser)$
windowrule = workspace 5, match:class ^(google-chrome)$
windowrule = workspace 6, match:class ^(signal)$
windowrule = workspace 2, match:class ^(krita)$
windowrule = workspace 8, match:class ^(brave-chat.openai.com__-Default)$
windowrule = workspace 8, match:class ^(brave-youtube.com__-Default)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = workspace 9, match:class ^(org.prismlauncher.PrismLauncher)$
windowrule = float on, match:class ^(org.prismlauncher.PrismLauncher)$, match:title ^(Console window.*)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, match:class ^(Btop)$
windowrule = size 1600 1000, match:class ^(Btop)$
windowrule = move 480 220, match:class ^(Btop)$
windowrule = float on, match:class ^(Nvtop)$
windowrule = size 1600 1000, match:class ^(Nvtop)$
windowrule = move 480 220, match:class ^(Nvtop)$


# windowrulev2 = float, title:^Webcam Viewer - Toggle Script$
# windowrulev2 = roundcorners 20, title:^Webcam Viewer - Toggle Script$
# windowrulev2 = size 640 480, title:^Webcam Viewer - Toggle Script$
# windowrulev2 = moveto 100 100, title:^Webcam Viewer - Toggle Script$
# windowrulev2 = pin, title:^Webcam Viewer - Toggle Script$

# windowrule = float, size 640 480, roundcorners 20, pin, title:^Webcam Viewer - Toggle Script$
windowrule = float on, match:title ^(Webcam Viewer - Toggle Script)$
windowrule = rounding 40, match:title ^(Webcam Viewer - Toggle Script)$

windowrule = float on, match:title ^(Webcam Viewer - FFPlay Toggle)$
windowrule = rounding 40, match:title ^(Webcam Viewer - FFPlay Toggle)$
windowrule = size 640 480, match:title ^(Webcam Viewer - FFPlay Toggle)$
windowrule = move 1900 60, match:title ^(Webcam Viewer - FFPlay Toggle)$

bind = $mainMod Shift, s, exec, ~/git/scripts/webcam_toggle.sh
bind = SUPER, SPACE, exec, hyprlauncher

# Cursor theme
env = XCURSOR_THEME,breeze_cursors
env = XCURSOR_SIZE,24

cursor {
    enable_hyprcursor = false
}
