# =====================================
# Hyprsunset Configuration
# =====================================
# Keep display color neutral by default.

# -------------------------------------
# Neutral profile
# -------------------------------------
profile {
    time = 00:00
    identity = true
}
