# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
# source = ~/.local/share/omarchy/default/hypr/autostart.conf
# source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
# source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
# source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
# source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
# source = ~/.local/share/omarchy/default/hypr/input.conf
# source = ~/.local/share/omarchy/default/hypr/windows.conf
# source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
# source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
# source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf


####################
### WINDOW RULES ###
####################
windowrulev2 = workspace 1, class:^(steam)$
windowrulev2 = workspace 4, class:^(kitty)$
windowrulev2 = workspace 5, class:^(firefox)$
windowrulev2 = workspace 5, class:^(brave-browser)$
windowrulev2 = workspace 5, class:^(google-chrome)$
windowrulev2 = workspace 6, class:^(signal)$
windowrulev2 = workspace 2, class:^(krita)$
windowrulev2 = workspace 8, class:^(brave-chat.openai.com__-Default)$
windowrulev2 = workspace 8, class:^(brave-youtube.com__-Default)$
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = workspace 9, class:^(org.prismlauncher.PrismLauncher)$
windowrulev2 = float, class:^(org.prismlauncher.PrismLauncher)$, title:^(Console window.*)$
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$

