# =====================================
# Hypridle Configuration
# =====================================

# -------------------------------------
# Active behavior
# -------------------------------------
general {
    lock_cmd = ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session               # lock before suspend.
    after_sleep_cmd = ~/.config/hypr/scripts/hyprctl.sh dispatch dpms on && brightnessctl -r && bluetoothctl connect F4:14:87:40:C1:93  # restore display, brightness, bluetooth after sleep
    inhibit_sleep = 3                                      # wait until screen is locked
}

# -------------------------------------
# Optional timeout listeners
# -------------------------------------
# listener {
#     timeout = 150                                           # 2.5min
#     on-timeout = pidof hyprlock || ~/.config/hypr/scripts/lock.sh
# }
#
# listener {
#     timeout = 300                                           # 5min
#     on-timeout = loginctl lock-session                      # lock screen when timeout has passed
# }
#
# listener {
#     timeout = 330                                           # 5.5min
#     on-timeout = ~/.config/hypr/scripts/hyprctl.sh dispatch dpms off                  # screen off when timeout has passed
#     on-resume = ~/.config/hypr/scripts/hyprctl.sh dispatch dpms on && brightnessctl -r && bluetoothctl connect F4:14:87:40:C1:93  # screen on, restore brightness, connect bluetooth
# }
#
# listener {
#     timeout = 900                                           # 15min
#     on-timeout = systemctl suspend                          # actually suspend the system
# }
