- hosts: localhost
  tasks:
    - name: Paru Core Desktop Install
      shell: >
        paru -Syu --noconfirm  arandr awesome bat blueman bluez bluez-utils brave-bin cargo direnv dkms dua-cli fd flameshot gimp github-cli gitui gpu-stat heroic-games-launcher-bin htop ijq jdk8-openjdk jre-openjdk-headless kitty lf linux-headers lolcat lxappearance man-db man-pages neofetch neovim-nightly-bin neovim-plug network-manager-applet nordic-theme noto-fonts nvm pavucontrol pcmanfm picom polybar pyenv ripgrep rofi rofimoji screenkey scrot starship steam stow the_silver_searcher timeshift tldr tmux tree ttf-dejavu ttf-iosevka-nerd ttf-liberation unzip viddy wmctrl xbindkeys xclip xpadneo-dkms.git yad zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting zsh-vi-mode dog inetutils docker-compose cloudflared bitwarden-cli-bin google-chrome openssh gthumb duf systemd-boot-pacman-hook zoom blockbench-bin


# cuda
# cudnn

# paru -Syu virt-manager qemu-desktop libvirt edk2-ovmf dnsmasq iptables jack2 --noconfirm
#
# sshfs
