- name: Install nodejs and npm
  become_user: root
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: Set Global npm directory
  shell: |
    mkdir ~/.local/.npm-global
    npm config set prefix '~/.local/.npm-global'
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: include node_modules path in .profile
  blockinfile:
    dest: "{{ lookup('env', 'HOME') }}/.profile"
    marker: '# {mark} npm-global bin added by devtainer'
    block: |
      # set PATH so it includes user's npm-global bin if it exists
      if [ -d "$HOME/.local/.npm-global/bin/" ] ; then
        PATH="$PATH:$HOME/.local/.npm-global/bin/"
      fi
    state: present
  become: yes
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: Install correct version of Node
  shell: "export N_PREFIX=~/.local/.n\nsudo ~/.local/.npm-global/bin/n 14 \n"
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
