close_when_open = true
theme = "default"
theme_base = []
theme_location = ["~/.config/walker/themes/"]
hotreload_theme = true
force_keyboard_focus = true
timeout = 60

[keys.ai]
run_last_response = ["ctrl e"]

[list]
max_entries = 200
cycle = true

[search]
placeholder = " Search..."

[builtins.hyprland_keybinds]
path = "~/.config/hypr/hyprland.conf"
hidden = true

[builtins.applications]
launch_prefix = "uwsm app -- "
placeholder = " Search..."
prioritize_new = false
context_aware = false
show_sub_when_single = false
history = false
icon = ""
hidden = false

[builtins.applications.actions]
enabled = false
hide_category = true

[builtins.bookmarks]
hidden = true

[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3
prefix = "="

[builtins.windows]
switcher_only = true
hidden = false

[builtins.clipboard]
hidden = true

[builtins.commands]
hidden = true

[builtins.custom_commands]
hidden = true

[builtins.emojis]
name = "Emojis"
icon = ""
prefix = ":"

[builtins.symbols]
after_copy = ""
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = true
hidden = false
prefix = "."

[builtins.runner]
shell_config = ""
switcher_only = true
hidden = true

[builtins.ssh]
hidden = true

[builtins.websearch]
switcher_only = true
hidden = true

[builtins.translation]
hidden = true
