- hosts: localhost
  tasks:
    - name: required libraries for brave
      become_user: root
      apt:
        name: ["curl", "apt-transport-https"]
      tags:
        - brave
        - install
    - name: Brave Browser archive-keyring.gpg download
      become_user: root
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      tags:
        - brave
        - install
    - name: Brave Browser PPA setting
      become_user: root
      shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
      tags:
        - brave
        - install
    - name: Brave Browser apt installation
      become_user: root
      apt:
        update_cache: yes
        name: brave-browser
      tags:
        - brave
        - install
