- hosts: localhost
  tasks:
    - name: install Steam
      become_user: root
      apt: name=steam-installer
      tags:
        - desktop
        - games
    - name: minecraft
      become_user: root
      community.general.snap:
        name: mc-installer
      tags:
        - desktop
        - games
