name: Build Docker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: waylonwalker/devtainer:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Build and push slim
        id: docker_build_slim
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile.slim
          push: true
          tags: waylonwalker/devtainer:slim
      - name: Image digest
        run: echo ${{ steps.docker_build_slim.outputs.digest }}
